-
  name: Apply for this opportunity
  editable: True
  questions:
    - availability
    - dayRate
    - essentialRequirementsMet
    - essentialRequirements
    - niceToHaveRequirements
    - respondToEmailAddress
