name: Environmentally-friendly working practices
question: Do you work in an environmentally-friendly way?
type: boolean
hint: Answer ‘yes’ if your organisation engages in working practices like recycling or lowering your carbon footprint.
assessment:
  passIfIn:
    - True
