name: Configuration and change management approach
question: Describe your configuration and change management processes.
question_advice: >
    Include details of how:

      - the components of your services are tracked through their lifetime
      - changes are assessed for potential security impact

depends:
  - "on": lot
    being:
      - cloud-hosting
      - cloud-software

type: textbox_large
max_length_in_words: 100

validations:
  - name: answer_required
    message: You need to answer this question.
  - name: under_100_words
    message: Your answer must be no longer than 100 words.
  - name: under_character_limit
    message: Your answer must be no longer than 1000 characters.
