requirements: 'Consumers should be sufficiently confident that configuration management processes are in place to ensure the integrity of the solution through development, testing and deployment.'
filters: 'Consumers should be sufficiently confident that configuration management processes are in place to ensure the integrity of the solution through development, testing and deployment.'
hint: 'Do you have configuration management in place to ensure the integrity of the service through development, testing and deployment?'
depends:
  -
    "on": lot
    being:
      - SaaS
      - saas
      - PaaS
      - paas
      - IaaS
      - iaas
assuranceApproach: 2answers-type1
type: boolean
validations:
  -
    name: answer_required
    message: 'You need to answer this question.'
  -
    name: assurance_required
    message: 'You need to confirm how you can back up your response.'
question: 'Software configuration management'
