-
  name: Page 1
  editable: True
  questions:
    - termsOfParticipation
    - termsAndConditions
    - davidKershaw
    - readUnderstoodGuidance
    - understandTool
    - understandHowToAskQuestions
    - environmentallyFriendly
    - consistentDelivery
    - continuousProfessionalDevelopment
    - customerSatisfactionProcess
    - skillsAndCapabilityAssessment
    - civilServiceValues
    - permanentMemberOfStaff
    - equalityAndDiversity
    - outcomes
    - specialists
    - researchStudios
    - participants
    - userNeeds
    - changesInNeeds
    - framingNeeds
    - freeAndOpenData
    - bespokeSystemInformation
    - openStandardsComponents
    - governmentsDesire
    - reusePurchasedAssets
    - governmentSecurityPrinciples
    - openStandardsPrinciples
    - openSourceLicence
    - safeguardPersonalData
    - incentives
    - safeguardData
    - safeguardOfficialInformation
    - hideGovernment
    - technologyCodesOfPractice
    - serviceStandard
    - ongoingEngagement
    - transparentContracting
    - publishContracts
    - canProvideFromDayOne
    - evidence
    - canProvideServices
    - skillsAndResources
    - accuratelyDescribed
    - proofOfClaims
    - MI
    - primaryContact
    - primaryContactEmail
    - nameOfOrganisation
    - registeredAddress
    - tradingStatus
    - tradingStatusOther
    - tradingNames
    - firstRegistered
    - firstRegisteredCountry
    - companyRegistrationNumber
    - registeredVATNumber
    - establishedInTheUK
    - appropriateTradeRegisters
    - appropriateTradeRegistersNumber
    - licenceOrMemberRequired
    - licenceOrMemberRequiredDetails
    - organisationSize
    - subcontracting
    - contactNameContractNotice
    - contactEmailContractNotice
    - cyberEssentials
    - cyberEssentialsPlus
    - employmentAgency
    - conspiracyCorruptionBribery
    - fraudAndTheft
    - terrorism
    - organisedCrime
    - taxEvasion
    - environmentalSocialLabourLaw
    - bankrupt
    - graveProfessionalMisconduct
    - distortingCompetition
    - conflictOfInterest
    - distortedCompetition
    - significantOrPersistentDeficiencies
    - seriousMisrepresentation
    - witheldSupportingDocuments
    - influencedContractingAuthority
    - confidentialInformation
    - misleadingInformation
    - mitigatingFactors
    - unspentTaxConvictions
    - GAAR
    - mitigatingFactors2
