-
  name: Title
  editable: True
  step: 1
  questions:
    - titleSpecialists
    - titleOutcomes
    - titleParticipants
-
  name: Specialist role
  editable: True
  step: 1
  questions:
    - specialistRole
-
  name: Location
  editable: True
  step: 1
  questions:
    - locationOutcomes
    - locationSpecialists
    - locationParticipants
-
  name: Description of work
  editable: True
  step: 1
  description: |
    This will help suppliers decide whether to apply.
  questions:
    - organisation
    - backgroundInformation
    - outcome
    - specialistWork
    - endUsers
    - earlyMarketEngagement
    - workAlreadyDone
    - phase
    - existingTeamOutcomes
    - existingTeamSpecialists
    - researchRounds
    - participantsPerRound
    - researchDates
    - researchFrequency
    - researchOutOfHours
    - researchAddress
    - accessRestrictions
    - participantSpecification
    - participantAccessibilityNeeds
    - researchPlan
    - workplaceAddress
    - workingArrangements
    - securityClearance
    - startDate
    - contractLength
    - additionalTerms
    - budgetRangeOutcomesParticipants
    - budgetRangeSpecialists
    - summary

-
  name: Shortlist criteria
  editable: True
  step: 2
  description: |
    After you’ve published your requirements, suppliers will apply and tell you:

    - when they can start work
    - if they have the essential skills and experience
    - which nice-to-have skills and experience they have

    You can shortlist the suppliers who:

    - can start work when you need them to
    - meet all the essential skills and experience
    - provide the most nice-to-have skills and experience

    [Read about how to shortlist.](https://www.gov.uk/guidance/how-to-shortlist-digital-outcomes-and-specialists-suppliers)
  questions:
    - essentialRequirementsOutcomes
    - niceToHaveRequirementsOutcomes
    - numberOfSuppliersOutcomes
-
  name: Shortlist criteria
  editable: True
  step: 2
  description: |
    After you’ve published your requirements, specialists will apply and tell you:

    - when they can start work
    - what their day rate is
    - if they have the essential skills and experience
    - which nice-to-have skills and experience they have

    You can shortlist the specialists who:

    - can start work when you need them to
    - are within your budget
    - meet all the essential skills and experience
    - provide the most nice-to-have skills and experience

    [Read about how to shortlist.](https://www.gov.uk/guidance/how-to-shortlist-digital-outcomes-and-specialists-suppliers)
  questions:
    - essentialRequirementsSpecialists
    - niceToHaveRequirementsSpecialists
    - numberOfSuppliersSpecialists
-
  name: Shortlist criteria
  editable: True
  step: 2
  description: |
    After you’ve published your requirements, suppliers will apply and tell you:

    - if they have the essential skills and experience
    - which nice-to-have skills and experience they have

    You can shortlist the suppliers who:

    - meet all the essential skills and experience
    - provide the most nice-to-have skills and experience

    [Read about how to shortlist.](https://www.gov.uk/guidance/how-to-shortlist-digital-outcomes-and-specialists-suppliers)
  questions:
    - essentialRequirementsParticipants
    - niceToHaveRequirementsParticipants
    - numberOfSuppliersParticipants

-
  name: Evaluation criteria
  editable: True
  step: 2
  description: |
    You need to tell suppliers how you’re going to evaluate them when you publish your requirements.

    To find the most suitable supplier, you must evaluate your shortlist on:

    - technical competence, using essential skills and experience, nice-to-have skills and experience, and their proposal
    - ‘cultural fit’, eg how the supplier will work in your organisation
    - the price of the proposal
  questions:
    - weightingOutcomes
    - essentialRequirementsOutcomes
    - niceToHaveRequirementsOutcomes
    - successCriteriaOutcomes
    - culturalFitCriteriaOutcomes
    - priceCriteria
    - evaluationTypeOutcomes

-
  name: Evaluation criteria
  editable: True
  step: 2
  description: |
    You need to tell suppliers how you’re going to evaluate them when you publish your requirements.

    To find the most suitable supplier, you must evaluate your shortlist on:

    - technical competence, using the specialists’ essential skills and experience, and nice-to-have skills and experience
    - ‘cultural fit’, eg how the supplier will work in your organisation
  questions:
    - weightingSpecialists
    - essentialRequirementsSpecialists
    - niceToHaveRequirementsSpecialists
    - culturalFitCriteriaSpecialists
    - evaluationTypeSpecialists

-
  name: Evaluation criteria
  editable: True
  step: 2
  description: |
    You need to tell suppliers how you’re going to evaluate them when you publish your requirements.

    To find the most suitable supplier, you must evaluate your shortlist on:

    - technical competence, using essential skills and experience, nice-to-have skills and experience, and their proposal
    - availability, eg whether the supplier can recruit user research participants when you need them
    - the price of the proposal
  questions:
    - weightingParticipants
    - essentialRequirementsParticipants
    - niceToHaveRequirementsParticipants
    - successCriteriaParticipants
    - evaluationTypeParticipants

-
  name: Describe question and answer session
  editable: True
  step: 3
  description: |
    While the application period is open, you need to reply to all questions suppliers ask about your requirements.

    When a supplier asks a question, you’ll be sent an email to the email address you registered with.

    You’ll need to post all questions and answers on the Digital Marketplace so that all suppliers can see them.

    Providing a question and answer session means you can explain your needs and answer any questions quickly.
  questions:
    - questionAndAnswerSessionDetails
