-
  name: Lab name
  editable: True
  questions:
    - serviceName

- name: Service essentials
  editable: True
  questions:
    - helpGovernmentImproveServices
    - bespokeSystemInformation
    - dataProtocols
    - openStandardsPrinciples
    - openSourceLicence

- name: User research participants essentials
  editable: True
  questions:
    - anonymousRecruitment
    - manageIncentives

- name: Team capabilities
  editable: True
  questions:
    - performanceAnalysisTypes
    - securityTypes
    - deliveryTypes
    - softwareDevelopmentTypes
    - supportAndOperationsTypes
    - testingAndAuditingTypes
    - userExperienceAndDesignTypes
    - userResearchTypes

- name: Outcomes locations
  editable: true
  questions:
    - outcomesLocations

- name: Agile coach
  editable: True
  questions:
    - agileCoachLocations
    - agileCoachDayRate

- name: Business analyst
  editable: True
  questions:
    - businessAnalystLocations
    - businessAnalystDayRate

- name: Content designer
  editable: True
  questions:
    - contentDesignerLocations
    - contentDesignerDayRate

- name: Cyber security consultant
  editable: True
  questions:
    - securityConsultantLocations
    - securityConsultantDayRate

- name: Delivery manager
  editable: True
  questions:
    - deliveryManagerLocations
    - deliveryManagerDayRate

- name: Designer
  editable: True
  questions:
    - designerLocations
    - designerDayRate

- name: Developer
  editable: True
  questions:
    - developerLocations
    - developerDayRate

- name: Communications manager
  editable: True
  questions:
    - communicationsManagerLocations
    - communicationsManagerDayRate

- name: Performance analyst
  editable: True
  questions:
    - performanceAnalystLocations
    - performanceAnalystDayRate

- name: Portfolio manager
  editable: True
  questions:
    - portfolioManagerLocations
    - portfolioManagerDayRate

- name: Product manager
  editable: True
  questions:
    - productManagerLocations
    - productManagerDayRate

- name: Programme manager
  editable: True
  questions:
    - programmeManagerLocations
    - programmeManagerDayRate

- name: Service manager
  editable: True
  questions:
    - serviceManagerLocations
    - serviceManagerDayRate

- name: Technical architect
  editable: True
  questions:
    - technicalArchitectLocations
    - technicalArchitectDayRate

- name: User researcher
  editable: True
  questions:
    - userResearcherLocations
    - userResearcherDayRate

- name: Web operations engineer
  editable: True
  questions:
    - webOperationsLocations
    - webOperationsDayRate

- name: Location
  editable: True
  questions:
    - labAddress
    - labPublicTransport
    - labCarPark
    - recruitLocations

- name: Lab size
  editable: True
  questions:
    - labSize

- name: Viewing
  editable: True
  questions:
    - labViewingArea
    - labStreaming
    - labDesktopStreaming
    - labDeviceStreaming
    - labEyeTracking
    - labWiFi

- name: Technical assistance
  editable: True
  questions:
    - labTechAssistance

- name: Hospitality
  editable: True
  questions:
    - labHosting
    - labWaitingArea

- name: Facilities
  editable: True
  questions:
    - labToilets
    - labBabyChanging

- name: Accessibility
  editable: True
  questions:
    - labAccessibility

- name: Price
  editable: True
  questions:
    - labPrice

- name: Recruitment approach
  editable: True
  questions:
    - recruitMethods
    - recruitFromList
