-
  name: View response to requirements
  questions:
    - supplierName
    - legacyAvailabilityOutcomes
    - legacyAvailabilitySpecialists
    - legacyDayRate
    - legacyNiceToHaveRequirements
    - legacyRespondToEmailAddress