-
  name: Apply for this opportunity
  editable: True
  description: "{% if lot == 'digital-specialists' %}You can only offer 1 specialist for this opportunity. {% endif %}Buyers will use the information suppliers provide here to create a shortlist."
  questions:
    - legacyRespondToEmailAddress
    - legacyEssentialRequirements
    - legacyNiceToHaveRequirements
    - legacyAvailabilityOutcomes
    - legacyAvailabilitySpecialists
    - legacyDayRate
