requirements: 'Service providers must state whether the service is a public, private or community cloud service.'
filters: 'Service providers must state whether the service is a public, private or community cloud service.'
hint: 'Is the service a public, private, community or hybrid cloud service?'
depends:
  -
    "on": lot
    being:
      - SaaS
      - PaaS
      - IaaS
assuranceApproach: 3answers-type1
type: radios
options:
    -
        label: 'Public cloud'
        filterLabel: 'Public cloud'
    -
        label: 'Community cloud'
        filterLabel: 'Community cloud'
    -
        label: 'Private cloud'
        filterLabel: 'Private cloud'
    -
        label: 'Hybrid cloud'
        filterLabel: 'Hybrid cloud'
validations:
  -
    name: answer_required
    message: 'You need to answer this question.'
  -
    name: assurance_required
    message: 'You need to confirm how you can back up your response.'
question: 'Cloud deployment model'
